// import { mockData } from "./mockData";

let mockData = [
  {
    id: 1,
    name: "Gerhardt",
    gender: "Male",
    nationality: "Colombia",
    degree: ["SSC", "HSC", "BSc", "MS"],
    address: "Room 268",
  },
  {
    id: 2,
    name: "Isidore",
    gender: "Male",
    nationality: "United States",
    degree: ["SSC", "HSC", "BSc"],
    address: "Apt 726",
  },
  {
    id: 3,
    name: "Constantin",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "12th Floor",
  },
  {
    id: 4,
    name: "Ham",
    gender: "Male",
    nationality: "France",
    degree: ["SSC", "HSC"],
    address: "14th Floor",
  },
  {
    id: 5,
    name: "Kimberlee",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "7th Floor",
  },
  {
    id: 6,
    name: "Tandie",
    gender: "Female",
    nationality: "Ivory Coast",
    degree: ["SSC", "HSC"],
    address: "PO Box 21331",
  },
  {
    id: 7,
    name: "Alasdair",
    gender: "Male",
    nationality: "Iran",
    degree: ["SSC", "HSC"],
    address: "Room 366",
  },
  {
    id: 8,
    name: "Fernando",
    gender: "Male",
    nationality: "Russia",
    degree: ["SSC", "HSC"],
    address: "Room 274",
  },
  {
    id: 9,
    name: "Moss",
    gender: "Male",
    nationality: "Philippines",
    degree: ["SSC", "HSC"],
    address: "Suite 76",
  },
  {
    id: 10,
    name: "Karlis",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "Suite 67",
  },
  {
    id: 11,
    name: "Lilas",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "PO Box 39801",
  },
  {
    id: 12,
    name: "Hershel",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "11th Floor",
  },
  {
    id: 13,
    name: "Cad",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Suite 78",
  },
  {
    id: 14,
    name: "Brigg",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Suite 77",
  },
  {
    id: 15,
    name: "Cesya",
    gender: "Female",
    nationality: "Israel",
    degree: ["SSC", "HSC"],
    address: "Apt 42",
  },
  {
    id: 16,
    name: "Even",
    gender: "Male",
    nationality: "Malaysia",
    degree: ["SSC", "HSC"],
    address: "PO Box 9981",
  },
  {
    id: 17,
    name: "Cassandra",
    gender: "Female",
    nationality: "Thailand",
    degree: ["SSC", "HSC"],
    address: "PO Box 48701",
  },
  {
    id: 18,
    name: "Essie",
    gender: "Female",
    nationality: "Slovenia",
    degree: ["SSC", "HSC"],
    address: "11th Floor",
  },
  {
    id: 19,
    name: "Bryanty",
    gender: "Male",
    nationality: "Philippines",
    degree: ["SSC", "HSC"],
    address: "PO Box 59001",
  },
  {
    id: 20,
    name: "Letta",
    gender: "Female",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "Apt 384",
  },
  {
    id: 21,
    name: "Ezri",
    gender: "Male",
    nationality: "Greece",
    degree: ["SSC", "HSC"],
    address: "19th Floor",
  },
  {
    id: 22,
    name: "Estevan",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Apt 1123",
  },
  {
    id: 23,
    name: "Moreen",
    gender: "Female",
    nationality: "Japan",
    degree: ["SSC", "HSC"],
    address: "Suite 85",
  },
  {
    id: 24,
    name: "Carmel",
    gender: "Female",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "Room 26",
  },
  {
    id: 25,
    name: "Lucho",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "Apt 1136",
  },
  {
    id: 26,
    name: "Marieann",
    gender: "Female",
    nationality: "Poland",
    degree: ["SSC", "HSC"],
    address: "Apt 1093",
  },
  {
    id: 27,
    name: "Koral",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Room 1788",
  },
  {
    id: 28,
    name: "Hakeem",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "PO Box 14123",
  },
  {
    id: 29,
    name: "Nelson",
    gender: "Male",
    nationality: "Venezuela",
    degree: ["SSC", "HSC"],
    address: "13th Floor",
  },
  {
    id: 30,
    name: "Banky",
    gender: "Male",
    nationality: "Azerbaijan",
    degree: ["SSC", "HSC"],
    address: "Room 727",
  },
  {
    id: 31,
    name: "Berri",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Suite 20",
  },
  {
    id: 32,
    name: "Meier",
    gender: "Male",
    nationality: "United Arab Emirates",
    degree: ["SSC", "HSC"],
    address: "Suite 83",
  },
  {
    id: 33,
    name: "Camel",
    gender: "Female",
    nationality: "Brazil",
    degree: ["SSC", "HSC"],
    address: "PO Box 22666",
  },
  {
    id: 34,
    name: "Melitta",
    gender: "Female",
    nationality: "Ukraine",
    degree: ["SSC", "HSC"],
    address: "Apt 937",
  },
  {
    id: 35,
    name: "Fin",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "15th Floor",
  },
  {
    id: 36,
    name: "Doti",
    gender: "Female",
    nationality: "Venezuela",
    degree: ["SSC", "HSC"],
    address: "Suite 98",
  },
  {
    id: 37,
    name: "Orel",
    gender: "Female",
    nationality: "Pakistan",
    degree: ["SSC", "HSC"],
    address: "Apt 1603",
  },
  {
    id: 38,
    name: "Franny",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "PO Box 42457",
  },
  {
    id: 39,
    name: "Bert",
    gender: "Male",
    nationality: "Syria",
    degree: ["SSC", "HSC"],
    address: "PO Box 63079",
  },
  {
    id: 40,
    name: "Berti",
    gender: "Male",
    nationality: "Russia",
    degree: ["SSC", "HSC"],
    address: "11th Floor",
  },
  {
    id: 41,
    name: "Elsworth",
    gender: "Male",
    nationality: "France",
    degree: ["SSC", "HSC"],
    address: "Room 1228",
  },
  {
    id: 42,
    name: "Normie",
    gender: "Male",
    nationality: "Nigeria",
    degree: ["SSC", "HSC"],
    address: "Apt 1244",
  },
  {
    id: 43,
    name: "Jaquelin",
    gender: "Female",
    nationality: "Ukraine",
    degree: ["SSC", "HSC"],
    address: "Apt 1158",
  },
  {
    id: 44,
    name: "Kendra",
    gender: "Female",
    nationality: "Russia",
    degree: ["SSC", "HSC"],
    address: "Apt 1495",
  },
  {
    id: 45,
    name: "Gabriel",
    gender: "Female",
    nationality: "Greece",
    degree: ["SSC", "HSC"],
    address: "PO Box 62222",
  },
  {
    id: 46,
    name: "Johanna",
    gender: "Female",
    nationality: "Sweden",
    degree: ["SSC", "HSC"],
    address: "Apt 1098",
  },
  {
    id: 47,
    name: "Brig",
    gender: "Male",
    nationality: "Poland",
    degree: ["SSC", "HSC"],
    address: "6th Floor",
  },
  {
    id: 48,
    name: "Leone",
    gender: "Female",
    nationality: "Poland",
    degree: ["SSC", "HSC"],
    address: "16th Floor",
  },
  {
    id: 49,
    name: "Putnem",
    gender: "Male",
    nationality: "Portugal",
    degree: ["SSC", "HSC"],
    address: "Room 492",
  },
  {
    id: 50,
    name: "Erick",
    gender: "Male",
    nationality: "Peru",
    degree: ["SSC", "HSC"],
    address: "Suite 39",
  },
  {
    id: 51,
    name: "Gabriela",
    gender: "Female",
    nationality: "Albania",
    degree: ["SSC", "HSC"],
    address: "9th Floor",
  },
  {
    id: 52,
    name: "Whittaker",
    gender: "Male",
    nationality: "United States",
    degree: ["SSC", "HSC"],
    address: "Apt 1395",
  },
  {
    id: 53,
    name: "Cariotta",
    gender: "Female",
    nationality: "Greece",
    degree: ["SSC", "HSC"],
    address: "8th Floor",
  },
  {
    id: 54,
    name: "Regine",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Room 1708",
  },
  {
    id: 55,
    name: "Wrennie",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Suite 8",
  },
  {
    id: 56,
    name: "Janek",
    gender: "Male",
    nationality: "Nicaragua",
    degree: ["SSC", "HSC"],
    address: "PO Box 93575",
  },
  {
    id: 57,
    name: "Cthrine",
    gender: "Female",
    nationality: "Greece",
    degree: ["SSC", "HSC"],
    address: "Suite 92",
  },
  {
    id: 58,
    name: "Bondie",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "PO Box 54005",
  },
  {
    id: 59,
    name: "Colas",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Room 1278",
  },
  {
    id: 60,
    name: "Buck",
    gender: "Male",
    nationality: "Albania",
    degree: ["SSC", "HSC"],
    address: "Suite 100",
  },
  {
    id: 61,
    name: "Frederica",
    gender: "Female",
    nationality: "Czech Republic",
    degree: ["SSC", "HSC"],
    address: "Suite 65",
  },
  {
    id: 62,
    name: "Giacopo",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Room 1287",
  },
  {
    id: 63,
    name: "Andris",
    gender: "Male",
    nationality: "Brazil",
    degree: ["SSC", "HSC"],
    address: "Room 879",
  },
  {
    id: 64,
    name: "Fern",
    gender: "Female",
    nationality: "Chile",
    degree: ["SSC", "HSC"],
    address: "10th Floor",
  },
  {
    id: 65,
    name: "Rafe",
    gender: "Male",
    nationality: "Honduras",
    degree: ["SSC", "HSC"],
    address: "Room 1045",
  },
  {
    id: 66,
    name: "Amata",
    gender: "Female",
    nationality: "United States",
    degree: ["SSC", "HSC"],
    address: "PO Box 13295",
  },
  {
    id: 67,
    name: "Hedwig",
    gender: "Female",
    nationality: "Lesotho",
    degree: ["SSC", "HSC"],
    address: "15th Floor",
  },
  {
    id: 68,
    name: "Leon",
    gender: "Male",
    nationality: "Albania",
    degree: ["SSC", "HSC"],
    address: "Apt 961",
  },
  {
    id: 69,
    name: "Valentijn",
    gender: "Male",
    nationality: "Russia",
    degree: ["SSC", "HSC"],
    address: "PO Box 4670",
  },
  {
    id: 70,
    name: "Yehudi",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "Apt 984",
  },
  {
    id: 71,
    name: "Ricard",
    gender: "Male",
    nationality: "Portugal",
    degree: ["SSC", "HSC"],
    address: "Apt 1041",
  },
  {
    id: 72,
    name: "Karon",
    gender: "Female",
    nationality: "France",
    degree: ["SSC", "HSC"],
    address: "Suite 52",
  },
  {
    id: 73,
    name: "Sollie",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "PO Box 65565",
  },
  {
    id: 74,
    name: "Guendolen",
    gender: "Female",
    nationality: "Zimbabwe",
    degree: ["SSC", "HSC"],
    address: "17th Floor",
  },
  {
    id: 75,
    name: "Bee",
    gender: "Female",
    nationality: "Myanmar",
    degree: ["SSC", "HSC"],
    address: "PO Box 33302",
  },
  {
    id: 76,
    name: "Paddy",
    gender: "Male",
    nationality: "Guatemala",
    degree: ["SSC", "HSC"],
    address: "5th Floor",
  },
  {
    id: 77,
    name: "Irita",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Room 1517",
  },
  {
    id: 78,
    name: "Jerri",
    gender: "Male",
    nationality: "Brazil",
    degree: ["SSC", "HSC"],
    address: "Suite 39",
  },
  {
    id: 79,
    name: "Clare",
    gender: "Female",
    nationality: "Russia",
    degree: ["SSC", "HSC"],
    address: "Apt 751",
  },
  {
    id: 80,
    name: "Seline",
    gender: "Female",
    nationality: "Bosnia and Herzegovina",
    degree: ["SSC", "HSC"],
    address: "9th Floor",
  },
  {
    id: 81,
    name: "Virginia",
    gender: "Female",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "Apt 412",
  },
  {
    id: 82,
    name: "Jeremiah",
    gender: "Male",
    nationality: "Sweden",
    degree: ["SSC", "HSC"],
    address: "Room 1577",
  },
  {
    id: 83,
    name: "Nils",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "PO Box 10710",
  },
  {
    id: 84,
    name: "Sayers",
    gender: "Male",
    nationality: "Croatia",
    degree: ["SSC", "HSC"],
    address: "PO Box 36889",
  },
  {
    id: 85,
    name: "Dedra",
    gender: "Female",
    nationality: "Morocco",
    degree: ["SSC", "HSC"],
    address: "Room 1498",
  },
  {
    id: 86,
    name: "Koenraad",
    gender: "Male",
    nationality: "China",
    degree: ["SSC", "HSC"],
    address: "6th Floor",
  },
  {
    id: 87,
    name: "Jordanna",
    gender: "Female",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "Apt 225",
  },
  {
    id: 88,
    name: "Lyn",
    gender: "Male",
    nationality: "Poland",
    degree: ["SSC", "HSC"],
    address: "Apt 1735",
  },
  {
    id: 89,
    name: "Laurie",
    gender: "Female",
    nationality: "Egypt",
    degree: ["SSC", "HSC"],
    address: "Suite 98",
  },
  {
    id: 90,
    name: "Mabel",
    gender: "Female",
    nationality: "Philippines",
    degree: ["SSC", "HSC"],
    address: "PO Box 11393",
  },
  {
    id: 91,
    name: "Kermy",
    gender: "Male",
    nationality: "Philippines",
    degree: ["SSC", "HSC"],
    address: "PO Box 32799",
  },
  {
    id: 92,
    name: "Patin",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "2nd Floor",
  },
  {
    id: 93,
    name: "Hanni",
    gender: "Female",
    nationality: "Austria",
    degree: ["SSC", "HSC"],
    address: "PO Box 80148",
  },
  {
    id: 94,
    name: "Nell",
    gender: "Female",
    nationality: "Maldives",
    degree: ["SSC", "HSC"],
    address: "PO Box 5188",
  },
  {
    id: 95,
    name: "Jon",
    gender: "Male",
    nationality: "Philippines",
    degree: ["SSC", "HSC"],
    address: "Suite 87",
  },
  {
    id: 96,
    name: "Shir",
    gender: "Female",
    nationality: "Honduras",
    degree: ["SSC", "HSC"],
    address: "Apt 1556",
  },
  {
    id: 97,
    name: "Chevy",
    gender: "Male",
    nationality: "Indonesia",
    degree: ["SSC", "HSC"],
    address: "PO Box 76228",
  },
  {
    id: 98,
    name: "Lynne",
    gender: "Female",
    nationality: "Poland",
    degree: ["SSC", "HSC"],
    address: "Room 1155",
  },
  {
    id: 99,
    name: "Noellyn",
    gender: "Female",
    nationality: "Myanmar",
    degree: ["SSC", "HSC"],
    address: "PO Box 8719",
  },
  {
    id: 100,
    name: "Fidelity",
    gender: "Female",
    nationality: "Portugal",
    degree: ["SSC", "HSC"],
    address: "Suite 94",
  },
];

const callApi = ({ url, params, data, method }) => {
  // return fetch(url , {
  //   params, data, method
  // })
};

export const getPersons = (filters) => {
  const result = mockData.filter((x) => {
    if (filters && Object.keys(filters).length > 0) {
      if (x.name && x.name.includes(filters.name)) return true;
      else if (x.gender && x.gender.includes(filters.gender)) return true;
      else if (x.nationality && x.nationality.includes(filters.nationality)) return true;
      else if (x.degree && x.degree.includes(filters.degree)) return true;
      else if (x.address && x.address.includes(filters.address)) return true;
      return false;
    }
    return true;
  });
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(result);
    }, 1 * 1000);
  });
};

export const deletePerson = (id) => {
  mockData = mockData.filter((x) => x.id !== id);
  return new Promise((resovle) => {
    resovle({ isDeleted: true });
  });
};
